### ISSUE TITLE
Not null fields

### ISSUE THREAD

**Issue by jhass** [amberframework/granite-orm#91] opened 2017-11-12 11:11 UTC
Having to handle `nil` on every field access is a PITA. Support marking fields as not null, or maybe even make that the default and support marking them as nullable. Make the primary key not null by default

**Comment by drujensen** [comment] 2017-11-12 14:29
yeah, crystal `.not_nil!` is very annoying.  I wish they chose something like swift using just an `!` or simpler syntax.

I have considered making the mapping more advanced and support `nilable` and other options that db's may support.  It would be an options hash per field.

**Comment by drujensen** [comment] 2017-11-12 14:30
closing since this is a duplicate of #57

**Closed by drujensen** 2017-11-12 14:30 UTC
